source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'MytelPayCSE' do
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', path: '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'RCTSettings',
    'DevSupport'
  ]

  pod 'Fabric', '~> 1.10.2'
  pod 'Crashlytics', '~> 3.13.2'
  # pod 'Firebase/Auth'
  pod 'Firebase/Core', '~> 6.3.0'
  pod 'GoogleIDFASupport', '~> 3.14.0'
  pod 'Firebase/Firestore', '~> 6.3.0'
  pod 'Firebase/Performance', '~> 6.3.0'
  pod 'Firebase/Messaging', '~> 6.3.0'
  # pod 'Firebase/RemoteConfig'
  # pod 'Firebase/DynamicLinks'
  # pod 'Bolts'
  # pod 'FBSDKCoreKit'
  # pod 'FBSDKShareKit'
  # pod 'FBSDKLoginKit'

  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'

  # for google sign_in
  # pod 'GoogleSignIn'
  # pod 'GoogleSymbolUtilities'
  # pod 'GoogleAppUtilities'
  # pod 'GoogleNetworkingUtilities'
  # pod 'GoogleUtilities'

  pod 'RNI18n', :path => '../node_modules/react-native-i18n'
  pod 'react-native-maps', path: '../node_modules/react-native-maps'
  pod 'react-native-google-maps', path: '../node_modules/react-native-maps'
  pod 'react-native-image-picker', path: '../node_modules/react-native-image-picker'
  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'
  pod 'react-native-fast-image', path: '../node_modules/react-native-fast-image'
  pod 'react-native-camera', path: '../node_modules/react-native-camera'
  pod 'RNKeychain', :path => '../node_modules/react-native-keychain'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
  pod 'react-native-webview', path: '../node_modules/react-native-webview'


  # CodePush plugin dependency
  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  pod 'Interactable', :path => '../node_modules/react-native-interactable'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  pod 'react-native-date-picker', :path => '../node_modules/react-native-date-picker'
  pod 'react-native-google-places', :path => '../node_modules/react-native-google-places'
  pod 'react-native-background-timer', :path => '../node_modules/react-native-background-timer'
  pod 'react-native-photo-view', path: '../node_modules/react-native-photo-view'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == "react-native-google-maps"
            target.build_configurations.each do |config|
                config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
            end
        end
        if target.name == "React"
          target.remove_from_project
        end
    end
end
